export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export const GET_WISHLIST = 'GET_WISHLIST';

export const FETCH_WISHLIST_PROPERTIES_REQUEST = "FETCH_WISHLIST_PROPERTIES_REQUEST";
export const FETCH_WISHLIST_PROPERTIES_SUCCESS = "FETCH_WISHLIST_PROPERTIES_SUCCESS";
export const FETCH_WISHLIST_PROPERTIES_FAILURE = "FETCH_WISHLIST_PROPERTIES_FAILURE";


export const ADD_PROPERTY_TO_WISHLIST_SUCCESS = "ADD_PROPERTY_TO_WISHLIST_SUCCESS";
export const ADD_PROPERTY_TO_WISHLIST_FAILURE= "ADD_PROPERTY_TO_WISHLIST_FAILURE";


// constants/WishlistConstants.js

export const COMPARE_WISHLIST_PROPERTIES_REQUEST = "COMPARE_WISHLIST_PROPERTIES_REQUEST";
export const COMPARE_WISHLIST_PROPERTIES_SUCCESS = "COMPARE_WISHLIST_PROPERTIES_SUCCESS";
export const COMPARE_WISHLIST_PROPERTIES_FAIL = "COMPARE_WISHLIST_PROPERTIES_FAIL";
