export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE';

export const GET_WISHLIST = 'GET_WISHLIST';

export const FETCH_WISHLIST_PROPERTIES_REQUEST = "FETCH_WISHLIST_PROPERTIES_REQUEST";
export const FETCH_WISHLIST_PROPERTIES_SUCCESS = "FETCH_WISHLIST_PROPERTIES_SUCCESS";
export const FETCH_WISHLIST_PROPERTIES_FAILURE = "FETCH_WISHLIST_PROPERTIES_FAILURE";